---

- hosts: dockerhosts
  tasks:
    - name: "Get uname -s"
      shell: uname -s
      register: unames
    - set_fact: uname_s={{unames.stdout}}
    
    - name: "Get uname -m"
      shell: uname -m
      register: unamem
    - set_fact: uname_m={{unamem.stdout}}

    - name: "Install docker compose."
      become: true
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{uname_s}}-{{uname_m}}
        dest: /usr/local/bin/docker-compose
        mode: 0755
